---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
