---
- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ compose_file }}"
  notify:
    - Restart Odoo
- name: Check if Odoo container is running
  command: docker ps --filter "name={{ project_name }}_odoo16" --format "{{
    '{{.Names}}' }}"
  register: odoo_container
  ignore_errors: true
- name: Stop and remove existing Odoo container
  command: docker-compose down
  args:
    chdir: "{{ ansible_user }}/opt/jenkins-training/jenskin_odoo"
  when: odoo_container.stdout == project_name + '_odoo16'
- name: Start Odoo container
  command: docker-compose up -d
  args:
    chdir: "{{ ansible_user }}/opt/jenkins-training/jenskin_odoo"
